# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20160519_0614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('text', 'list')]),
        ),
    ]
